PORTNAME=	feluda
DISTVERSION=	1.5.2
CATEGORIES=	textproc

MAINTAINER=	nxjoseph@protonmail.com
COMMENT=	Detect license usage restrictions in your project
WWW=		https://github.com/anistark/feluda

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cargo ssl
USE_GITHUB=	yes
GH_ACCOUNT=	anistark

PLIST_FILES=	bin/${PORTNAME}

.include <bsd.port.mk>
