PORTNAME=	musicbrainzngs
DISTVERSION=	0.7.1
CATEGORIES=	www python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nxjoseph@protonmail.com
COMMENT=	Python bindings for the MusicBrainz NGS
WWW=		https://github.com/alastair/python-musicbrainzngs \
		https://pypi.org/project/musicbrainzngs

LICENSE=	BSD2CLAUSE ISCL
LICENSE_COMB=	multi
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		python:3.4+
USE_PYTHON=	autoplist distutils flavors

NO_ARCH=	yes
NO_BUILD=	yes
NO_INSTALL=	yes

.include <bsd.port.mk>
